apiVersion: v1
kind: ServiceAccount
metadata:
  name: localstack
  labels:
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/name: localstack
    app.kubernetes.io/version: latest
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/name: localstack
    app.kubernetes.io/version: latest
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - name: edgeport
      port: 4566
      targetPort: 4566
      nodePort: 31566
    - name: esport
      port: 4571
      targetPort: 4571
      nodePort: 31571
  selector:
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/name: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app.kubernetes.io/instance: localstack
    app.kubernetes.io/name: localstack
    app.kubernetes.io/version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: localstack
      app.kubernetes.io/name: localstack
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: localstack
        app.kubernetes.io/name: localstack
    spec:
      serviceAccountName: localstack
      securityContext: {}
      containers:
        - name: localstack
          securityContext: {}
          image: "localstack/localstack:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: edgeport
              containerPort: 4566
              protocol: TCP
            - name: esport
              containerPort: 4571
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: edgeport
          readinessProbe:
            httpGet:
              path: /health
              port: edgeport
          resources: {}
          env:
            - name: DEBUG
              value: "0"
              # Hostname exposed internally.  Used for framework internal communication i.e. docker-compose.
            - name: HOSTNAME
              value: "localstack"
              # Hostname exposed externally.  Used when returning URL for SQS service
            - name: HOSTNAME_EXTERNAL
              value: "localstack"
              # If changing this, you'll have to change it across the project!
            - name: DEFAULT_REGION
              value: "us-east-1"