github:
        prebuilds:
                master: true
                branches: false
                pullRequests: true
                pullRequestsFromForks: false
                addCheck: true
                addComment: false
                addBadge: false
image:
        file: .gitpod.Dockerfile
tasks:
        - name: Run localstack
          init: >
                  DEBUG=1 localstack start -d
